// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Display$RescriptIntro from "./Display.bs.js";
import * as DigitButton$RescriptIntro from "./DigitButton.bs.js";
import * as OperationButton$RescriptIntro from "./OperationButton.bs.js";

function Calculator(Props) {
  return React.createElement("div", {
              className: "p-4 grid grid-cols-5 gap-2 rounded shadow bg-gradient-to-br from-indigo-400 to-pink-400 animate-gradient"
            }, React.createElement(Display$RescriptIntro.make, {
                  text: "0"
                }), React.createElement(DigitButton$RescriptIntro.make, {
                  digit: /* Digit */{
                    _0: 7
                  }
                }), React.createElement(DigitButton$RescriptIntro.make, {
                  digit: /* Digit */{
                    _0: 8
                  }
                }), React.createElement(DigitButton$RescriptIntro.make, {
                  digit: /* Digit */{
                    _0: 9
                  }
                }), React.createElement(OperationButton$RescriptIntro.make, {
                  operation: /* Clear */0
                }), React.createElement(OperationButton$RescriptIntro.make, {
                  operation: /* Add */3
                }), React.createElement(DigitButton$RescriptIntro.make, {
                  digit: /* Digit */{
                    _0: 4
                  }
                }), React.createElement(DigitButton$RescriptIntro.make, {
                  digit: /* Digit */{
                    _0: 5
                  }
                }), React.createElement(DigitButton$RescriptIntro.make, {
                  digit: /* Digit */{
                    _0: 6
                  }
                }), React.createElement(OperationButton$RescriptIntro.make, {
                  operation: /* Divide */1
                }), React.createElement(DigitButton$RescriptIntro.make, {
                  digit: /* Digit */{
                    _0: 3
                  }
                }), React.createElement(DigitButton$RescriptIntro.make, {
                  digit: /* Digit */{
                    _0: 2
                  }
                }), React.createElement(DigitButton$RescriptIntro.make, {
                  digit: /* Digit */{
                    _0: 1
                  }
                }), React.createElement(OperationButton$RescriptIntro.make, {
                  operation: /* Multiply */2
                }), React.createElement(OperationButton$RescriptIntro.make, {
                  operation: /* Equals */5
                }), React.createElement(DigitButton$RescriptIntro.make, {
                  digit: /* ZeroDigit */0
                }), React.createElement(DigitButton$RescriptIntro.make, {
                  digit: /* Dot */1
                }), React.createElement(OperationButton$RescriptIntro.make, {
                  operation: /* Subtract */4
                }));
}

var make = Calculator;

export {
  make ,
  
}
/* react Not a pure module */
