// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Digit$RescriptIntro from "./Digit.bs.js";
import * as Button$RescriptIntro from "./Button.bs.js";

function DigitButton(Props) {
  var digit = Props.digit;
  var className = digit === 0 ? "bg-white col-span-2" : "bg-white";
  return React.createElement(Button$RescriptIntro.make, {
              text: Digit$RescriptIntro.toString(digit),
              className: className
            });
}

var make = DigitButton;

export {
  make ,
  
}
/* react Not a pure module */
