// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Digit$RescriptIntro from "./Digit.bs.js";
import * as Button$RescriptIntro from "./Button.bs.js";

function DigitButton(Props) {
  var digit = Props.digit;
  var send = Props.send;
  var className = digit === 0 ? "bg-white col-span-2" : "bg-white";
  var text = Digit$RescriptIntro.toString(digit);
  return React.createElement(Button$RescriptIntro.make, {
              text: text,
              className: className,
              onClick: (function (param) {
                  return Curry._1(send, {
                              TAG: /* DigitPressed */0,
                              _0: digit
                            });
                })
            });
}

var make = DigitButton;

export {
  make ,
  
}
/* react Not a pure module */
