// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Display(Props) {
  var text = Props.text;
  return React.createElement("div", {
              className: "col-span-5 text-2xl font-black shadow-sm text-right text-white bg-indigo-900 p-4 rounded"
            }, text);
}

var make = Display;

export {
  make ,
  
}
/* react Not a pure module */
