// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Button$RescriptIntro from "./Button.bs.js";
import * as Operation$RescriptIntro from "./Operation.bs.js";

function OperationButton(Props) {
  var operation = Props.operation;
  var className;
  switch (operation) {
    case /* Clear */0 :
        className = "bg-yellow-500";
        break;
    case /* Divide */1 :
    case /* Multiply */2 :
    case /* Subtract */4 :
        className = "bg-yellow-200";
        break;
    case /* Add */3 :
    case /* Equals */5 :
        className = "bg-yellow-200 row-span-2";
        break;
    
  }
  return React.createElement(Button$RescriptIntro.make, {
              text: Operation$RescriptIntro.toString(operation),
              className: className
            });
}

var make = OperationButton;

export {
  make ,
  
}
/* react Not a pure module */
