// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Button(Props) {
  var text = Props.text;
  var classNameOpt = Props.className;
  var onClick = Props.onClick;
  var className = classNameOpt !== undefined ? classNameOpt : "bg-white";
  return React.createElement("button", {
              className: "p-4 text-2xl font-bold shadow-sm active:scale-95 active:-rotate-1 hover:shadow-xl duration-75 hover:scale-105 hover:rotate-1 rounded text-center " + className,
              onClick: onClick
            }, text);
}

var make = Button;

export {
  make ,
  
}
/* react Not a pure module */
