// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function stateToString(state) {
  if (typeof state === "number") {
    return "0";
  }
  switch (state.TAG | 0) {
    case /* Operating */1 :
        var secondDigits = state._2;
        if (secondDigits === "") {
          return state._0;
        } else {
          return secondDigits;
        }
    case /* Typing */0 :
    case /* Result */2 :
        return state._0;
    
  }
}

function Display(Props) {
  var state = Props.state;
  return React.createElement("div", {
              className: "bg-opacity-75 col-span-5 text-2xl font-black shadow text-right text-white bg-indigo-900 p-4 mb-2 rounded"
            }, stateToString(state));
}

var make = Display;

export {
  stateToString ,
  make ,
  
}
/* react Not a pure module */
