// Generated by ReScript, PLEASE EDIT WITH CARE


function calculate(a, operation, b) {
  var firstFloat = Number(a);
  var secondFloat = Number(b);
  var tmp;
  switch (operation) {
    case /* Divide */1 :
        tmp = firstFloat / secondFloat;
        break;
    case /* Multiply */2 :
        tmp = firstFloat * secondFloat;
        break;
    case /* Add */3 :
        tmp = firstFloat + secondFloat;
        break;
    case /* Subtract */4 :
        tmp = firstFloat - secondFloat;
        break;
    case /* Clear */0 :
    case /* Equals */5 :
        tmp = secondFloat;
        break;
    
  }
  return String(tmp);
}

export {
  calculate ,
  
}
/* No side effect */
