// Generated by ReScript, PLEASE EDIT WITH CARE


function toString(digit) {
  if (typeof digit === "number") {
    if (digit !== 0) {
      return ".";
    } else {
      return "0";
    }
  } else {
    return String(digit._0);
  }
}

export {
  toString ,
  
}
/* No side effect */
