// Generated by ReScript, PLEASE EDIT WITH CARE


function toString(operation) {
  switch (operation) {
    case /* Clear */0 :
        return "C";
    case /* Divide */1 :
        return "/";
    case /* Multiply */2 :
        return "*";
    case /* Add */3 :
        return "+";
    case /* Subtract */4 :
        return "-";
    case /* Equals */5 :
        return "=";
    
  }
}

export {
  toString ,
  
}
/* No side effect */
