// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function App(Props) {
  return React.createElement("div", {
              className: "flex justify-center items-center h-screen"
            }, "ReScript React with Tailwind running on Vite");
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
