// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Calculator$RescriptIntro from "./calculator/Calculator.bs.js";

function App(Props) {
  return React.createElement("div", {
              className: "bg-indigo-50 flex flex-col justify-center items-center h-screen"
            }, React.createElement("div", {
                  className: "pb-8 drop-shadow-xl text-5xl text-transparent font-extrabold bg-clip-text bg-gradient-to-br from-pink-400 to-indigo-400 animate-gradient"
                }, "ReScript Calculator"), React.createElement(Calculator$RescriptIntro.make, {}));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
