// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

function use(initialState, handleEvent) {
  var match = React.useState(function () {
        return initialState;
      });
  var setState = match[1];
  var state = match[0];
  var send = function ($$event) {
    return Curry._1(setState, (function (param) {
                  return Curry._2(handleEvent, state, $$event);
                }));
  };
  return [
          state,
          send
        ];
}

export {
  use ,
  
}
/* react Not a pure module */
