// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Machine$RescriptIntro from "./Machine.bs.js";

function handleOnEvent(currentState, $$event) {
  if ($$event) {
    return /* Off */1;
  } else {
    return currentState;
  }
}

function handleOffEvent(currentState, $$event) {
  if ($$event) {
    return currentState;
  } else {
    return /* On */0;
  }
}

function handleEvent(currentState, $$event) {
  if (currentState) {
    if ($$event) {
      return currentState;
    } else {
      return /* On */0;
    }
  } else if ($$event) {
    return /* Off */1;
  } else {
    return currentState;
  }
}

function stateToString(state) {
  if (state) {
    return "Off";
  } else {
    return "On";
  }
}

function ToggleMachine(Props) {
  var match = Machine$RescriptIntro.use(/* On */0, handleEvent);
  var send = match[1];
  return React.createElement("div", {
              className: "flex flex-col justify-center items-center p-4"
            }, React.createElement("div", {
                  className: "text-xl"
                }, match[0] ? "Off" : "On"), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(send, /* TurnOn */0);
                    })
                }, "Turn on"), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(send, /* TurnOff */1);
                    })
                }, "Turn off"));
}

var make = ToggleMachine;

export {
  handleOnEvent ,
  handleOffEvent ,
  handleEvent ,
  stateToString ,
  make ,
  
}
/* react Not a pure module */
